### ISSUE TITLE
any plan to support Exo 2.0

### ISSUE THREAD

**Issue by calber** [ant-media/LibRtmp-Client-for-Android#17]
will you do it ?

(2.0 is a kind of major with lot of fixes)

**Comment by mekya** [comment]
This rtmp library actually is independent of ExoPlayer.

Have you tested that this library does not work on Exo 2.0?

Bests,
A. Oguz

**Comment by calber** [comment]
tested and not compatible, major changes in exo 2.0...

**Comment by PanCrucian** [comment]
any plan to support Exo 2.1.0? I tested too and this RTMPClient not compatible with Exo

**Comment by micHar** [comment]
I tried to implement it based on the exoplayer 1.x sample.


    
    public class RtmpDataSource implements DataSource {

    private final RtmpClient rtmpClient;
    private Uri uri;

    public RtmpDataSource(Uri uri) {
        this.uri = uri;
        rtmpClient = new RtmpClient();
    }

    @Override
    public long open(DataSpec dataSpec) throws IOException {
        rtmpClient.open(dataSpec.uri.toString(), false);
        return C.LENGTH_UNSET;
    }

    @Override
    public void close() throws IOException {
        rtmpClient.close();
    }

    @Override
    public int read(byte[] buffer, int offset, int readLength) throws IOException {
        return rtmpClient.read(buffer, offset, readLength);

    }

    @Override
    public Uri getUri() {
        return uri;
    }
    }


Then tried to use it like this:


        DataSource.Factory dataSourceFactory = () -> new RtmpDataSource(Uri.parse(mediaUrl));
        Handler mainHandler = new Handler();
        ExtractorMediaSource source = new ExtractorMediaSource(Uri.parse(mediaUrl), dataSourceFactory, new DefaultExtractorsFactory(), mainHandler, null);
        player.prepare(source);
        player.setPlayWhenReady(true);


But it didn't work for me. It was a blind guess, though. Any ideas?

**Comment by mekya** [comment]
Sorry i don't have any idea right now. 

Nevertheless, i want to make it compatible with ExoPlayer 2.0,  I don't have time to do that in these days.

Sorry for that

**Comment by micHar** [comment]
I'm willing to help, but to be honest I'm not really an expert when it comes to streaming, so you would have to point me in the right direction. Right now I'm kind of stuck with the code above.

**Comment by mekya** [comment]
I am sorry for the late reply. 

Exoplayer 2 is now supported. 

FYI

**Comment by ojw28** [comment]
FYI, we're planning to merge https://github.com/google/ExoPlayer/pull/2503 into ExoPlayer, which will allow you to plug LibRtmp into any version of ExoPlayer (starting from the version where it's added).
