### ISSUE TITLE
there is around 10 sec delay time after it plays

### ISSUE THREAD

**Issue by dirablue** [ant-media/LibRtmp-Client-for-Android#19]
Hi 

thank you for your library.
I was looking for RTMP player for Android.

it can play the RTMP Live and the video.
but if I play the live, it took around 10 sec delay time.

how can I reduce this time to around 3sec ?

I changed buffer time of ExoPlayer, but it didn't affect.

**Comment by mekya** [comment]
Hi Dirablue,

I think this is probably to your network speed or rtmp server because we got 1-2 seconds delay in live stream if there is high network speed with this library https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek

**Comment by mekya** [comment]
Closing issue, if you have a question please let me know
