### ISSUE TITLE
Effective bitrate

### ISSUE THREAD

**Issue by kelmer44** [ant-media/LibRtmp-Client-for-Android#22]
Is there a way to obtain the real bitrate resulting from the streaming? 

I am encoding separately and from Android 4.3 there is the option of changing bitrate mid-stream so I would like for the library to let me know of the real bitrate in order to change this on-the-fly.

Thanks!

**Comment by kelmer44** [comment]
Ok I checked and there is none but do you know how to implement that with librtmp? On the native code itself?

**Comment by mekya** [comment]
You can count how many bytes you have sent and divide it into time. If there is slow internet connection, writeVideo and writeAudio files takes more time to return for the RTMPMuxer

**Comment by kelmer44** [comment]
Thanks I did just dad successfully :)


Is it also possible to know when the client is disconnected? I know there is a isConnected method but is it possible to have a callback whenever the client gets disconnected?

**Comment by mekya** [comment]
In our app, we have a timer, it shows the elapsed time in the screen and it is updated in every second. In addition, we check if client is still connected to the server in this timer task, you may use a similar aproach as well. 

Moreover, if it is critical for you, we may think adding a listener interface to the library that is called when clients get disconnected.

Closing issue, please open it, if you have an issue.
