### ISSUE TITLE
UnsatisfiedLinkError without abifilters

### ISSUE THREAD

**Issue by micHar** [ant-media/LibRtmp-Client-for-Android#25]
When I use your lib as a gradle dependency, it crashes at runtime with UnsatisfiedLinkError:

    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file ".../base.apk"],nativeLibraryDirectories=[.../lib/arm64, .../base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "librtmp-jni.so"
                                                             at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                             at java.lang.System.loadLibrary(System.java:1530)
                                                             at net.butterflytv.rtmp_client.RtmpClient.<clinit>(RtmpClient.java:9)

It's here:

    static {
        System.loadLibrary("rtmp-jni");
    }

It works when I add abiFilters (tested od Nexus 5X which handles e.g. armeabi-v7a).

    defaultConfig {
        ...
        ndk {
            abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        }
    }

But it doesn't make sense to me. Why does adding abifilter change anything? If you understand it, maybe there should be some mention in readme about it.

**Comment by mekya** [comment]
I think, your app has both armeabi and armeabi-v7a folders or something like that. 

All libraries should be under each directory. For instance think that a library has only compiled for armeabi but system is armeabi-v7a and there is an another library which is compiled for armeabi-v7a version. In this scenario there will be unsatisfiedlink error like above
