### ISSUE TITLE
Crash when using ExoPlayer-with-RTMP-and-FLV-seek demo

### ISSUE THREAD

**Issue by dfpro** [ant-media/LibRtmp-Client-for-Android#28]
Thanks for your excellent library and demo, it crashes when I start PlayerActivity and then finish it on and on, and the logs are as below,

com.google.android.exoplayer.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 2134 (RenderThread)

please tell me how to resolve it.

Thanks again!

**Comment by mekya** [comment]
Hi @dfpro,

Unfourtunately, I cannot say something specific. I need to test and find the bug you reported. For now, as you know,  it is about memory problem. Library tried to access a memory location that is not allocated or freed. 

I hope i will find sometime to fix these issues in near future. 

Sorry.

**Comment by mekya** [comment]
Closing issue if you have any question, please let me know

Btw, there are some updates in the repo, these updates may already fix your issue.
