### ISSUE TITLE
How does network failure work?

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#30]
RtmpClient.open has a few error codes that indicate when establishing the connection fails. However I cannot see any way for RtmpClient to indicate connectivity issues to the caller after the connection is established.

If you've managed to open a connection, read() just returns 0 repeatedly if the connection is subsequently killed (e.g. by putting the device in airplane mode). I would expect read() to throw some kind of IOException in this case. I would also expect open() to throw IOException rather than returning an integer, since it makes it far less likely that the caller will forget to handle failure, but that's more debatable :).

Thoughts? Would it be possible to have read() indicate failure properly?

**Comment by mekya** [comment]
Yeah you are right, read function throws exception if connection to server is lost somehow. Check the commit referenced above. Also check the #31 issue.

Returning different values for open function makes easy to debug the problem, nevertheless yeah I may implement to make the open function throw IOException in any failure.

**Comment by ojw28** [comment]
One option would be to make an RtmpIOException, like:

```
class RtmpIOException extends IOException {

    public final static int OPEN_ALLOC = -1;
    public final static int OPEN_SETUP_URL = -2;
    public final static int OPEN_CONNECT = -3;
    public final static int OPEN_CONNECT_STREAM = -4;

    public final int errorCode;

    public RtmpIOException(int errorCode) {
      this.errorCode = errorCode;
    }

  }
```

Then you could both throw and make it easy for the caller to retrieve the error code (if open is defined to throw RtmpIOException specifically).

**Comment by mekya** [comment]
Check it out https://github.com/ant-media/LibRtmp-Client-for-Android/commit/4afe5ce95b891ca478ac94983b92443ee6d6f2d1

**Comment by ojw28** [comment]
Cool! Thanks. I posted a couple of notes on the change.
