### ISSUE TITLE
Under what conditions can RtmpClient.read() return 0 bytes?

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#31]
Most Java APIs for reading data (e.g. InputStream and all subclasses) are blocking, meaning they either (a) read at least one byte, (b) fail by throwing an exception, (c) return -1 to indicate the end of the data has been reached.

It's undocumented whether RtmpClient.read() can return 0 or not, meaning that no bytes have been read. It appears that it can, from experimentation. Please could:

- The behaviour of read() be clearly documented. It's unclear whether returning 0 is allowed just by looking at the documentation.
- Ideally read() would have behaviour like InputStream. If it is allowed to return 0 then a caller may end up needing to implement a while loop that basically polls (and consumes CPU) until data can be read. Which is far from ideal.

**Comment by mekya** [comment]
read function is documented.

**Comment by ojw28** [comment]
It would be more standard to return -1 instead of 0 for the end-of-stream case, since that matches what Java's InputStream class does. Whether you want to change it I guess depends on how you feel about changing the API, although given you're already making some API changes for the next release, it would be a good time to make this change also if you ever intend to do so :).

**Comment by mekya** [comment]
hi @ojw28, please check this commit https://github.com/ant-media/LibRtmp-Client-for-Android/commit/5371bf782a4a909cfa3514886ee978a1cb5ff7b5
