### ISSUE TITLE
Add RtmpClient.open return values to the API

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#32]
RtmlClient.open has Javadoc that defines a number of possible return values:
```
     * -1 RTMP_Alloc error
     * -2 RTMP_SetupURL error
     * -3 RTMP_Connect error
     * -4 RTMP_ConnectStream error
```
Could these be exposed in the RtmpClient API as `public static final int` constants, so that code using RtmpClient can reference them rather than having to define their own?

**Comment by ojw28** [comment]
Note: The "success" return value should also be a constant.

**Comment by mekya** [comment]
A new commit has been pushed for this issue.
4d95bf62d405dd615c4647d6ff8a87f0b1c1bfc6

is it ok for you?

**Comment by ojw28** [comment]
Yes, thanks!

**Comment by mekya** [comment]
Closing issue.
