### ISSUE TITLE
Include 64-bit libraries in releases

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#33]
The aar for the most recent release ([here](https://bintray.com/mekya/maven/rtmp-client/0.2.6.1#files/net/butterflytv/utils/rtmp-client/0.2.6.1)) only contains 32-bit .so files in the jni directory.

This means the RTMP library fails to load with UnsatisfiedLinkError if the application using the library also uses any other dependency that does contain 64-bit .so files. This happens because Android cannot load 32-bit and 64-bit libraries concurrently, as described [here](https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html). There are hacky workaround to this issue, but they're really not ideal.

Please could you include 64-bit variant .so files in the release? Thanks!

**Comment by mekya** [comment]
Yeah you are right, when do you need to get this issue done? Is it urgent?

**Comment by ojw28** [comment]
We're looking at adding an RTMP extension to ExoPlayer that has a dependency on this project. It's not urgent other than we have developers who want (and will be happy with) such an extension :).

I think we'd want this issue and also #30 / #31 / #32 fixed before we go ahead and commit, so from our perspective we'd rather see a release that takes a bit longer and fixes all four than a quick release that fixes this issue only. Lack of error propagation from read() and read() being able to return 0 are particularly problematic.

**Comment by ojw28** [comment]
Note: You could potentially release both 32bit only and 32+64bit modules, if you want the option of keeping the size small for applications for whom the existing release works correctly.

**Comment by mekya** [comment]
After resolving #30 and #31, I can publish a new version for 32bit only and 32+64bit modules.
