### ISSUE TITLE
How to implement librtmp on Android application?

### ISSUE THREAD

**Issue by Nezne1k4** [ant-media/LibRtmp-Client-for-Android#35]
I checkout the rtmp-client project and find that there is no code in `test module` just the `rtmp-client` is baked already, which is pretty awesome.
However, I don't know to to implement to show RTMP on a player or videoview.
What I tried is:
- open rtmp client to RTMP url (a valid url like rtmp://127.0.0.1/live/mytest)
- check that client is open.
- able to read() which returns an int value.

`byte[] buffer = new byte[1024];
int readData = rtmpClient.read(buffer, 0, 1024);`

Can anyone guide what I should do to render data from read() function to the video view?
Thanks.

**Comment by mekya** [comment]
Hi, There is another repository to play rtmp on Android which is
https://github.com/ant-media/ExoPlayer-with-RTMP-and-FLV-seek

You may also take a look at this repo which both broadcast and play livestream
https://github.com/ant-media/LiveVideoBroadcaster

**Comment by Nezne1k4** [comment]
@mekya Thanks for your information. I will check those repositories out.
