### ISSUE TITLE
multi streams playing at the same time

### ISSUE THREAD

**Issue by Andywzg** [ant-media/LibRtmp-Client-for-Android#37]
I will do a demo app which contains multi video windows to show several rtmp live streams. I can play only one rtmp stream now, how could I create multi clients at the same time ?

**Comment by mekya** [comment]
Please check this issue https://github.com/ant-media/LibRtmp-Client-for-Android/issues/40

**Comment by mekya** [comment]
We can continue talking this issue on the #40 thread, so I am closing this issue. Please open it if you have any other problem.
