### ISSUE TITLE
Are there any docs on how to capture camera and send as rtmp stream?

### ISSUE THREAD

**Issue by mohsalsaleem** [ant-media/LibRtmp-Client-for-Android#38]
I have a SurfaceTextureView on which the camera feed is shown. I read the camera feed as ImageReader. Once I receive a frame, I want to send it as an RTMP stream to my server. I see that there is a writeVideo method, which accepts H264 nal units. But, I'm unsure how to convert camera stream to that. Can you please point me in a direction where I can find some resources or give me an example?

**Comment by mekya** [comment]
Hi @mohsalsaleem , take a look at the sample repo 
https://github.com/ant-media/LiveVideoBroadcaster
and a blog post
http://antmedia.io/how-to-develop-a-live-streaming-mobile-app-in-3-steps/

if you have any other question, please let me know. If you need instant support, please let me know your email address to send a slack invitation.

Bests,
A. Oguz

**Comment by mohsalsaleem** [comment]
Thanks a lot. That'll help.
