### ISSUE TITLE
minSdkVersion set too high

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#39]
I see it got set to 21 due to some issue around allowing the NDK to generate resources for newer architectures.

That doesn't sound right, since the result is that anything depending on this library must also have minSdkVersion set to at least 21. This in turn implies any app using this library cannot support anything prior to Lollipop. Is that really intentional/required?

**Comment by mekya** [comment]
Actually it was 18, however arm64, etc. libraries are only generated at sdk
level 21 and I updated it according to your request at #33

Do you have a solution for that?

**Comment by ojw28** [comment]
It appears this was a bug with the gradle plugin, which is now marked as fixed. I'm don't really have any experience working with the NDK, but see these links, and I hope they're sufficient to enable you to figure it out :)...

https://b.corp.google.com/issues/37071489
https://stackoverflow.com/questions/41102128/android-ndk-how-to-build-for-arm64-v8a-with-minimumsdkversion-19

If not then let me know, and I'll ask around!

**Comment by mekya** [comment]
OK thank you:) I will take a look.

which SDK level is ok for you?

**Comment by ojw28** [comment]
You should just set it to the minimum that the library needs, not the minimum that a particular user of the library needs ;).

**Comment by mekya** [comment]
it is good to hear that ;)

**Comment by ojw28** [comment]
This is blocking us launching our ExoPlayer RTMP extension. Do you have any kind of an ETA for providing a fix? Thanks.

**Comment by mekya** [comment]
I will try to fix this issue in a couple of days. I have a busy timeline. Sorry for that.

**Comment by mekya** [comment]
There is a new commit for this. https://github.com/ant-media/LibRtmp-Client-for-Android/commit/664a1f19edc2570f6f2df99172596ffb8fbf2845 check this out.

**Comment by ojw28** [comment]
Thanks!

**Comment by mekya** [comment]
Never mind. Btw, sorry again for busy schedule.

**Comment by mekya** [comment]
Closing the issue. If there is a problem for you, please re-open it or create an issue

**Comment by ojw28** [comment]
Thanks!
