### ISSUE TITLE
Can't play some rtmp stream: RtmpIOException

### ISSUE THREAD

**Issue by Ryder68** [ant-media/LibRtmp-Client-for-Android#41]
Hi.
I'm using ExoPlayer RTMP extension (r2.5.1): https://github.com/google/ExoPlayer/tree/dev-v2/extensions/rtmp
This link: **rtmp://studiosystem.co.in:1935/v4news/livestream** => **play OK**
This link: **rtmp://video.f10.bdpcdn.net:1935/vod/mp4:Media/2017/08/09/14/cn9-809082017.mp4** => **_play ERROR_** but  **play OK** in other players: _vitamio, vlc,..._
Logcat: 

```
ExoPlayerImplInternal: Source error.
   net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
	   at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:53)
	   at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
	   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
	   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
	   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	   at java.lang.Thread.run(Thread.java:841)
```

Please help me!
Thanks.

P/s: Demo that link **play OK** on VLC:

![image](https://user-images.githubusercontent.com/30622400/29149096-f9a10f76-7d9b-11e7-8fad-080f3b5bc389.png)

**Comment by mekya** [comment]
Hi @Ryder68 ,

As this library is a wrapper of librtmp client. It mainly inherits same behaviours from librtmp. For the url you provided cannot be parsed correctly by librtmp, so we need to help librtmp to parse it correctly.

In short, to play such a url you provided, you should add the playpath variable to the url like below. Pay attention that there is a space between rtmp url and the playpath variable.

> `"rtmp://video.f10.bdpcdn.net/vod/mp4:Media/2017/08/09/14/cn9-809082017.mp4 playpath=/mp4:Media/2017/08/09/14/cn9-809082017.mp4"`

I have tested the url above and it is playing for me. I hope it will play for you as well.  

--
Quick Info:
> **playpath=path**
> Overrides the playpath parsed from the RTMP URL. Sometimes the rtmpdump URL parser cannot determine the correct playpath automatically, so it must be given explicitly using this option.

For more info take a look at the documentation 
https://rtmpdump.mplayerhq.hu/librtmp.3.html

**Comment by Ryder68** [comment]
Hi @mekya 
I tried adding playpath and it played well, although it was inconvenient.
Tks so much! <3

**Comment by mekya** [comment]
I couldn't even play this url(rtmp://118.107.84.3/live/vtc11_public) with VLC.

I think we can add this parameter automatically to the url so that it will become convenient for you ;)

**Comment by Ryder68** [comment]
@mekya  Thank you so much.
If can, please add that parameter automatically in this lib.
In addition, if same as that link  then playpath will look like ?
Ex: 
`rtmp://125.212.132.219:1935/standard/_definst_/mp4:standard_720p`
=>` rtmp://125.212.132.219:1935/standard/_definst_/mp4:standard_720p playpath=???`

`rtmp://118.107.84.3/live/vtc11_public `
=> `rtmp://118.107.84.3/live/vtc11_public playpath=???`

**Comment by mekya** [comment]
@Ryder68 
if I played these urls somehow with VLC or something else, I would find out the playpath

Have you played the urls you have provided in any media player?

**Comment by Ryder68** [comment]
@mekya 
I played that stream in VLC on windows 7.
This is screenshot:
`rtmp://125.212.132.219:1935/standard/_definst_/mp4:standard_720p`

![image](https://user-images.githubusercontent.com/30622400/29345152-f55845b8-8266-11e7-80cf-bcf6c035796c.png)

**Comment by mekya** [comment]
I event succeed to play on VLC in mac however it starts to play too late. It does not play smoothly either.
Anyway, I tried to play on Exoplayer. It gives an error in audio track.

> 08-16 09:48:07.037 27806-27806/com.google.android.exoplayer2.demo E/EventLogger: internalError [21.36, audioTrackUnderrun [61568, 320, 527]]

This error is out of scope of this library. 

Let me say something about playpath, if there is a "mp4:" in the url and and the url does not finish with "mp4:..." then librtmp does not correctly parse the url and playpath should be provided.

**Comment by Ryder68** [comment]
I understand.
Thank you so much.
Have a nice day <3

**Comment by mekya** [comment]
You're welcome, 
Closing issue, just ping me if you have any question.

btw, we provide media server and sdks at http://antmedia.io . If you want to subscribe to newsletter for new updates, please send an e-mail to contact at antmedia dot io

Thank you

Regards,

**Comment by guodong1111** [comment]
@mekya 
I am sorry to trouble you. I have the same problem in this link: 
rtmp://sicbo:sicbo@lcstest.sp2001.com:1935/live/sicbo01.stream
But this link works in other app & ios player.
Can you help me to solve this problem?

**Comment by kmasterycsl** [comment]
For someone still faces this issue. 
Try append to the url like this  `"rtmp://URL live=1" `
