### ISSUE TITLE
Not connect with _definst_

### ISSUE THREAD

**Issue by DemindoO** [ant-media/LibRtmp-Client-for-Android#42]
This client does not work if  it has _definst_ in url 
I tried this sample demo application 
https://github.com/ant-media/ExoPlayer-with-RTMP-and-FLV-seek

and this link its perfectly work in VLC andriod app stream-> url 

rtmp://pkpipe.com:1935/vod/\_definst\_/test/1.mp4

**Comment by mekya** [comment]
Please try this way 
"rtmp://pkpipe.com:1935/vod/_definst_/test/1.mp4 app=vod playpath=test/1.mp4"

Please let me know if it works

**Comment by mekya** [comment]
Closing this issue.
