### ISSUE TITLE
Reopen of #21 Writing frames returns -1

### ISSUE THREAD

**Issue by brestmoor** [ant-media/LibRtmp-Client-for-Android#43]
I would like to have another question to the return codes of `writeVideo`.
I will copy here the question i posted to the already closed issue:

Hi,

Could you please look at this fragment of code?

this is a `onActivityResult` method of my activity:

```java
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(requestCode == 1 && resultCode == RESULT_OK) {
            Uri videoUri = data.getData();
            InputStream inputStream = getInputStreamFromUri(videoUri, getContentResolver());

            rtmpMuxer.open("rtmp://192.168.1.108/live/Gg", 320, 240);

            byte[] chunk = new byte[4096];
            int counter = 0;
            try {
                while (inputStream.read(chunk, 0, 4096) > 0) {
                    counter++;
                    System.out.println("video succeeded " + rtmpMuxer.writeVideo(chunk, 0, 4096, counter));
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
```
So, the server I am broadcasting to works fine, I have tested it, and the file that is represented as `inputStream` and then divided into `chunk`s is a .h264 file. I got it by using ffmpeg on an .mp4 file.

So my goal here is to read the file from android external storage, and then broadcast it 
chunk by chunk.

However the `writeVideo` fails to send most of the chunks. This is what console looks like

> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded 0
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded 0
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded -1
> 08-21 21:03:29.080 26684-26684/projekt.filip.raspberry I/System.out: video succeeded 0

Am I missing something here? Do you have any idea how to solve it? Any advice will be higly appriciated.

I tried LiveVideoBroadcaster and it works great, but it doesn't fit what I need because my goal is to send files from android storage.

**Comment by mekya** [comment]
Hi @brestmoor ,

In order to use RtmpMuxer, you need the read packets(aka tags) from flv file and then write them to the RtmpMuxer.  Each packet has a specific size and type(video and audio). 

If you have a h264 file, then you need to get each NAL unit from this file and send to the rtmpmuxer as NAL units. In h264 file each NAL unit starts with 0x000001 or 0x00000001.  It seems that you need to dig into the NAL units.

Regards,

**Comment by brestmoor** [comment]
Ok, splitting the h264 file into NAL units almost completly solved this issue. Now I get almost always 0-s, the only -1-s I get is at the beginning of the file for 2 or 3 pockets, but that maybe is not an issue.

Although I would like to ask you for advice with another place where I got stuck, which is, the pockets i send (NALs) cannot be read by a client which is VLC player.

Do you think that my pockets somehow are too large? I would say the average size is about 23kb. Or do I do something wrong again with pocketizing the data?

Here I link the VLC debug logs: https://pastebin.com/JBtsAKWQ

**Comment by mekya** [comment]
Hi @brestmoor ,

The ordering of packets may cause rtmp write function to return -1 so it makes a player to stuck.

In LiveVideoBroadcaster there is a simple ordering functionality. 

https://github.com/ant-media/LiveVideoBroadcaster/blob/master/liveVideoBroadcasterSDK/src/main/java/io/antmedia/android/broadcaster/network/RTMPStreamer.java

You may use rtmp_write in the same way LiveVideoBroadcaster uses 
https://github.com/ant-media/LiveVideoBroadcaster/

Please let me know your thoughts. I want to help.

**Comment by brestmoor** [comment]
Hi @mekya 

Unfortunatelly that project that I was working on went to an end, but if I get some free time I will check if reordering pockets helps here :).

Thanks for your response.

This rtmp topic seems very complicated in general.

**Comment by mekya** [comment]
Yeah it is a little bit complicated. I can help you more if you have any question. 
I can share my personal phone number as well for chatting and phone call.
