### ISSUE TITLE
Question about timestamp in rtmpMuxer

### ISSUE THREAD

**Issue by maxdylan** [ant-media/LibRtmp-Client-for-Android#47]
Normal timestamp is long, but in rtmpMuxer.write() the timestamp is int. What is the timestamp mean in function write? I use System.current() or SystemClock.es... sometimes work but sometime return -1. The timestamp puzzled me.
Forgive my poor English, sorry.
Thank you a lot.

**Comment by mekya** [comment]
Hi @maxdylan ,

timestamp is the time of the frame in milliseconds. If a frame's timestamp is equal or less than the previous frame,  servers generally does not accept that packet and write functions returns -1

You may take a look at how it is used in this repo. 
https://github.com/ant-media/LiveVideoBroadcaster

Regards,
A. Oguz

**Comment by maxdylan** [comment]
thank you very much

**Comment by mekya** [comment]
You're welcome :)
