### ISSUE TITLE
Native code crash with unreachable rtmp server

### ISSUE THREAD

**Issue by nagendraK6** [ant-media/LibRtmp-Client-for-Android#53]
I am using exoplayer with librtmp fpr my RTMP server. It works fine if rtmp url is reachable. If rtmp server is down or shutdown then my app crash with following code crash.

01-23 22:37:20.565 31883-31883/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-23 22:37:20.565 31883-31883/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170720.005/4205617:user/release-keys'
01-23 22:37:20.582 31883-31883/? A/DEBUG: Revision: '0'
01-23 22:37:20.582 31883-31883/? A/DEBUG: ABI: 'x86'
01-23 22:37:20.582 31883-31883/? A/DEBUG: pid: 31745, tid: 31825, name: Loader:Extracto  >>> com.relylabs.phirki <<<
01-23 22:37:20.582 31883-31883/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa7f1f4c
01-23 22:37:20.582 31883-31883/? A/DEBUG:     eax 59005f60  ebx 94200000  ecx 0007ffff  edx 00000071
01-23 22:37:20.582 31883-31883/? A/DEBUG:     esi 0007ffff  edi b17e2778
01-23 22:37:20.582 31883-31883/? A/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
01-23 22:37:20.582 31883-31883/? A/DEBUG:     eip b1795e92  ebp 8f5fa6c8  esp 8f5fa670  flags 00010a07
01-23 22:37:20.586 31883-31883/? A/DEBUG: backtrace:
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #00 pc 00090e92  /system/lib/libc.so (arena_run_dalloc+114)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #01 pc 0008c24b  /system/lib/libc.so (arena_dalloc_large_locked_impl+251)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #02 pc 0008c13b  /system/lib/libc.so (je_arena_dalloc_large_junked_locked+43)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #03 pc 000b01ba  /system/lib/libc.so (je_tcache_bin_flush_large+330)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #04 pc 000b127f  /system/lib/libc.so (tcache_destroy+623)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #05 pc 000b0ff4  /system/lib/libc.so (je_tcache_cleanup+36)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #06 pc 000b1a80  /system/lib/libc.so (je_tsd_cleanup+64)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #07 pc 000b2adc  /system/lib/libc.so (je_tsd_cleanup_wrapper+44)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #08 pc 00071124  /system/lib/libc.so (_Z21pthread_key_clean_allv+164)
01-23 22:37:20.586 31883-31883/? A/DEBUG:     #09 pc 00070b59  /system/lib/libc.so (pthread_exit+89)
01-23 22:37:20.587 31883-31883/? A/DEBUG:     #10 pc 000709bd  /system/lib/libc.so (_ZL15__pthread_startPv+61)
01-23 22:37:20.587 31883-31883/? A/DEBUG:     #11 pc 0002050b  /system/lib/libc.so (__start_thread+75)
01-23 22:37:20.587 31883-31883/? A/DEBUG:     #12 pc 0001eda6  /system/lib/libc.so (__bionic_clone+70)
01-23 22:37:22.969 31893-31900/? E/zygote: Failed sending reply to debugger: Broken pipe

I can repro this issue 100% of the case.

**Comment by mekya** [comment]
It should be fixed with version 3.0.1, please use the latest lib ;)

**Comment by mekya** [comment]
Please open it if you have tested 3.0.1 and not working for you
