### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4244 in tid 438 (Thread-1159)

### ISSUE THREAD

**Issue by ianholing** [ant-media/LibRtmp-Client-for-Android#61]
Hi there,
I found this issue and it was giving me lot of headaches in a production App during weeks. It doesn't even show any crash analytics tools, it simply stops and it was completely random and not really frequent.

![error](https://user-images.githubusercontent.com/5333567/37823050-9ae38e5c-2e88-11e8-947a-8aea1c7f63da.png)

What happens here is that "zeros_in_startcode" is always 3, but "buf" is an offset inside the array which can be the last item.. so "buf[zeros_in_startcode]" can access memory out of the allocated memory. Even accessing memory outside the boundaries it does not crash always, only when that memory is a protected zone.

**Comment by ianholing** [comment]
I made a pull request with my proposal:
https://github.com/ant-media/LibRtmp-Client-for-Android/pull/62

Thank you for your great work with this library.

**Comment by mekya** [comment]
Thank you. Your PR has been merged.
