### ISSUE TITLE
RtmpClient.open hangs forever when connecting to invalid address

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#67]
This occurs with 3.0.1. When connecting to `rtmp://184.72.232.149/vod/mp4:blah.mp4`, which is an invalid address, `RtmpClient.open` hangs forever somewhere in `nativeOpen`.  It should be throwing an `RtmpIOException` in this case.

Please could you take a look at this; it's trivial to reproduce.

**Comment by ojw28** [comment]
Any update on this? And on the other issues we've filed. We've seen quite a few problems with LibRtmp use via ExoPlayer. If they're not going to be fixed any time soon then it would be good to know, so we can explore alternative options. Thanks.

**Comment by ojw28** [comment]
@mekya - Please could you provide an update? Thanks!

**Comment by ojw28** [comment]
@mekya - Any update? If you're no longer working on this project / supporting it, that would be good to know too. Thanks.

**Comment by mekya** [comment]
@ojw28 sorry for late reply. I am highly loaded about streaming project and I do not have so much bandwidth. 
I am willing to take a look at this issue. On the other hand, I think at least I need 2 weeks to allocate some time for this project. If it is ok for you, I can schedule this issue for 2 weeks. 
Any PR is welcome btw.

**Comment by ojw28** [comment]
@mekya - Could you please provide an update, as above. If the project is dead, we'd like to know. Thanks.
