### ISSUE TITLE
RtmpClient.read returns -1 rather than throwing when no connection

### ISSUE THREAD

**Issue by ojw28** [ant-media/LibRtmp-Client-for-Android#69]
Reproduction steps:

1. Start reading an RTMP live stream, by opening a connection and then repeatedly calling `RtmpClient.read`, as normal. @jinfanzon can provide you with such a stream via email.
1. Toggle airplane mode on, then off again whilst reading.
1. Observe the current `RtmpClient.read` call ends up returning -1, which is documented to mean that the stream is complete.

It looks to me like returning -1 in this case is incorrect. In ExoPlayer, it causes us to assume the stream has ended and transition the player to its ended state. The `RtmpClient.read` call should either throw an exception (in which case the player will retry) or read some valid data (if possible, depending on when the method returns relative to when airplane mode is toggled off again). Please could you take a look?

**Comment by mekya** [comment]
Hi,
Throwing an exception indicating connection with the server is dropped may help you for this issue?

**Comment by ojw28** [comment]
Yes, if `RtmpClient.read` were to throw an appropriate exception rather than returning -1 in this case, that would help.

**Comment by jinfanzon** [comment]
Hi @mekya - could you please provide me an email adress to send the stream url I'm using.
